JupiterOne/graph-rapid7

CHANGELOG.md
package.json
src/steps/__snapshots__/index.test.ts.snap
src/steps/vulnerabilities.ts
yarn.lock

Upgrading SDK since this work was done a little while back.

Upgrade SDK@v5.2.0

---

src/constants.ts
src/steps/access.ts
src/steps/account.ts
src/steps/asset-users.ts
src/steps/assets.ts
src/steps/scan-assets.ts
src/steps/scans.ts
src/steps/site-assets.ts
src/steps/site-users.ts
src/steps/sites.ts
src/steps/vulnerabilities.ts

A few explicit dependencies were not present in this integration. It most likely wouldn't have made a big impact in the dependency graph, but worth doing.
Split into two commits - check the first for dependency changes.

Update step depends on

---

CHANGELOG.md
CODEOWNERS
package.json
src/client.ts
src/steps/__snapshots__/index.test.ts.snap
src/steps/access.ts
src/steps/account.ts
src/steps/asset-users.ts
src/steps/assets.ts
src/steps/scan-assets.ts
src/steps/scans.ts
src/steps/site-assets.ts
src/steps/site-users.ts
src/steps/sites.ts
src/steps/vulnerabilities.ts
src/validateInvocation.ts

We know there is an issue in this step that prevents the integration from terminating. The changes here can help us answer the following questions:
1. Is there an issue when trying to fetch a new page of vulnerabilities?
2. Is there an issue when we try to find an existing vulnerability?

Log client activity

---

docs/jupiterone.md

removing a duplicate header and adding some auth info

Update rapid7 docs with auth

---

.github/workflows/build.yml

fix build release

---

CHANGELOG.md
package.json

Release 0.5.1

---

src/steps/scans.ts

Omitting scans if we've already saved them to the jobState

---

src/client.ts
src/error.ts

INT-8945 - adjust error handling and handle econnreset errors

---

CHANGELOG.md
package.json

Release v0.5.6

---

src/config.ts

Collectors don't explicitly set this by default so the field needs to be marked as optional and fallback on the default value of falsiness
API
match the recommended model for this …

Make TLS verification config optional

---

CHANGELOG.md
console/scripts/start-console.sh
docs/jupiterone.md
package.json
src/config.ts
src/constants.ts
src/index.ts
src/ingestionConfig.ts
src/steps/__snapshots__/asset-users.test.ts.snap
src/steps/__snapshots__/site-assets.test.ts.snap
src/steps/access.ts
src/steps/assets.ts
src/steps/scans.ts
src/steps/sites.ts
src/steps/vulnerabilities.ts
src/types.ts
yarn.lock

update repo to publish collector image

---

src/config.ts

fix config field type from boolean to string

---

src/client.ts
src/constants.ts
src/steps/assets.ts
src/steps/vulnerabilities.ts

filter vulnerabilities out by severity before requests

---

src/constants.ts
src/steps/assets.ts
src/steps/vulnerabilities.ts

disable indexMetadata on selected entities and relationships

---

Dockerfile
src/client.ts
src/steps/vulnerabilities.ts

collector
API
relationships, and their property names, to …

add debug log to inspect memory and entities/relationships count on

---

Dockerfile
src/steps/vulnerabilities.ts

change log from debug to info

---

src/client.ts
src/steps/vulnerabilities.ts

add debug log to evaluate optimization change

---

src/steps/vulnerabilities.ts

add vulnRequests count for debug

---

src/steps/vulnerabilities.ts

add total findings debug log

---

.gitignore
src/client.ts
src/steps/vulnerabilities.test.ts
src/steps/vulnerabilities.ts

change to iterate over all vulns instead of fetching one by one

---

src/config.ts
src/steps/vulnerabilities.ts
src/utils.ts

log USE_ON_DISK_DKT env var
